# -*- coding: utf-8 -*-
"""YOLO11_infer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhTf9UIl8zYGKnJ-Vq4v6wr-0yaAksAS
"""

from ultralytics import YOLO

# Load your trained YOLO11m classification model
model = YOLO("/Users/satvikaakati/Desktop/yolo_project/runs/classify/train2/weights/best.pt")

# Path to an image or folder to test
source = "/Users/satvikaakati/datasets/cifar10/test/airplane/0001.png"  # example image

# Run inference
results = model.predict(source=source, imgsz=160, device='mps', save=True)

# Print top predictions
for r in results:
    print(r.probs.top1, r.names[r.probs.top1], f"({r.probs.top1conf*100:.2f}% confidence)")