# -*- coding: utf-8 -*-
"""YOLO11_CIFAR10_robust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18APjk0lYrbSk2dU50x0n8tMV8GJ1NKHa

# YOLOv11m-cls on CIFAR-10 (blur-robust)

This notebook trains and evaluates a blur-robust YOLOv11 classifier on CIFAR-10.
- Model: `yolo11m-cls` (use `yolo11l-cls` if you can afford more compute for a small accuracy gain)
- Input size: 160 (upsample 32×32 → 160)
- Strong regularization and cosine LR schedule for generalization on blurred images.
"""

# Commented out IPython magic to ensure Python compatibility.
# Setup
# %pip -q install -U ultralytics

from ultralytics import YOLO
import torch

# Device selection prioritizing Apple Silicon (MPS), then CUDA, else CPU
if torch.backends.mps.is_available():
    device = "mps"
elif torch.cuda.is_available():
    device = 0  # first CUDA device
else:
    device = "cpu"

device

# Training: YOLOv11m-cls on CIFAR-10 with stronger regularization
from ultralytics import YOLO

# Load pretrained ImageNet weights for classification
model = YOLO("yolo11m-cls.pt")

# Stronger setup for small, blurred CIFAR-10
# If you hit OOM, reduce batch from 256 -> 128 or 64.
results = model.train(
    data="cifar10",       # auto-downloads if missing
    imgsz=160,            # upsample 32 -> 160 improves accuracy
    epochs=20,
    batch=256,
    optimizer="AdamW",
    lr0=0.003,
    lrf=0.1,             # final LR as fraction of lr0
    weight_decay=0.05,
    warmup_epochs=3,
    patience=30,
    label_smoothing=0.10,
    dropout=0.10,
    mixup=0.10,
    cutmix=0.20,
    erasing=0.40,
    cos_lr=True,
    device=device,
    seed=0,
    verbose=True,
)
results = model.val(data='cifar10', split='test')
print(results)

print("Training complete. Run dir:", results.save_dir)

# Evaluation on CIFAR-10 test split (Top-1 / Top-5)
from ultralytics import YOLO
import torch

try:
    _ = model
except NameError:
    model = YOLO("yolo11m-cls.pt")

if torch.backends.mps.is_available():
    device = "mps"
elif torch.cuda.is_available():
    device = 0
else:
    device = "cpu"

metrics = model.val(data="cifar10", split="test", imgsz=160, device=device)
print({"top1": float(metrics.top1), "top5": float(metrics.top5)})

# Robustness demo: Gaussian blur inference on a few CIFAR-10 test images
import os
import cv2
from ultralytics import YOLO
from ultralytics.utils import SETTINGS

try:
    _ = model
except NameError:
    model = YOLO("yolo11m-cls.pt")

# Resolve datasets directory used by Ultralytics
datasets_dir = SETTINGS.get("datasets_dir", os.path.expanduser("datasets"))
test_dir = os.path.join(datasets_dir, "cifar10", "test")

samples = [
    os.path.join(test_dir, "airplane", "0001.png"),
    os.path.join(test_dir, "bird", "0001.png"),
    os.path.join(test_dir, "horse", "0001.png"),
]

for src in samples:
    if not os.path.exists(src):
        print("Missing sample:", src)
        continue
    img = cv2.imread(src)
    blurred = cv2.GaussianBlur(img, (7, 7), 2.0)
    tmp_path = "_tmp_blur.png"
    cv2.imwrite(tmp_path, blurred)
    print("Blurred inference for:", src)
    _ = model(tmp_path, imgsz=160, save=False, device='cpu')

try:
    os.remove("_tmp_blur.png")
except Exception:
    pass